### ISSUE TITLE
Gateway4 on VLAN isn't saved

### ISSUE THREAD

**Issue by enricobachiorrini** [linux-system-roles/network#413] opened 2021-08-03 16:38 UTC
Hello,

My `network_connections` look like this:
```
network_connections:
  - name: bond0
    state: up

  - name: bond0.1000
    state: up
    type: vlan
    parent: bond0
    vlan:
      id: 1000
    ip:
      address:
        - 10.68.97.3/31
      gateway4: 10.68.97.2
```

which result in the creation of the following interface:

```
===============================================================================
                    Connection profile details (bond0.1000)
===============================================================================
connection.id:                          bond0.1000
connection.uuid:                        6a9696b4-55c4-4cfc-be7e-2ceb83ad46e6
connection.stable-id:                   --
connection.type:                        vlan
connection.interface-name:              bond0.1000
connection.autoconnect:                 yes
connection.autoconnect-priority:        0
connection.autoconnect-retries:         -1 (default)
connection.multi-connect:               0 (default)
connection.auth-retries:                -1
connection.timestamp:                   1628007401
connection.read-only:                   no
connection.permissions:                 --
connection.zone:                        --
connection.master:                      --
connection.slave-type:                  --
connection.autoconnect-slaves:          -1 (default)
connection.secondaries:                 --
connection.gateway-ping-timeout:        0
connection.metered:                     unknown
connection.lldp:                        default
connection.mdns:                        -1 (default)
connection.llmnr:                       -1 (default)
connection.wait-device-timeout:         -1
-------------------------------------------------------------------------------
802-3-ethernet.port:                    --
802-3-ethernet.speed:                   0
802-3-ethernet.duplex:                  --
802-3-ethernet.auto-negotiate:          no
802-3-ethernet.mac-address:             --
802-3-ethernet.cloned-mac-address:      --
802-3-ethernet.generate-mac-address-mask:--
802-3-ethernet.mac-address-blacklist:   --
802-3-ethernet.mtu:                     auto
802-3-ethernet.s390-subchannels:        --
802-3-ethernet.s390-nettype:            --
802-3-ethernet.s390-options:            --
802-3-ethernet.wake-on-lan:             default
802-3-ethernet.wake-on-lan-password:    --
-------------------------------------------------------------------------------
ipv4.method:                            manual
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.addresses:                         10.68.97.3/31
ipv4.gateway:                           --
ipv4.routes:                            --
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.routing-rules:                     --
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-iaid:                         --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.dhcp-hostname-flags:               0x0 (none)
ipv4.never-default:                     yes
ipv4.may-fail:                          yes
ipv4.dad-timeout:                       -1 (default)
ipv4.dhcp-vendor-class-identifier:      --
-------------------------------------------------------------------------------
ipv6.method:                            auto
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.addresses:                         --
ipv6.gateway:                           --
ipv6.routes:                            --
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.routing-rules:                     --
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.ra-timeout:                        0 (default)
ipv6.dhcp-duid:                         --
ipv6.dhcp-iaid:                         --
ipv6.dhcp-timeout:                      0 (default)
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.dhcp-hostname-flags:               0x0 (none)
ipv6.token:                             --
-------------------------------------------------------------------------------
vlan.parent:                            ad33d8b0-1f7b-cab9-9447-ba07f855b143
vlan.id:                                1000
vlan.flags:                             1 (REORDER_HEADERS)
vlan.ingress-priority-map:              --
vlan.egress-priority-map:               --
-------------------------------------------------------------------------------
proxy.method:                           none
proxy.browser-only:                     no
proxy.pac-url:                          --
proxy.pac-script:                       --
-------------------------------------------------------------------------------
```

The problem is that `ipv4.gateway` is null. Setting it manually with `nmcli con mod bond0.1000 ipv4.gateway 10.68.97.2` after the interface was created won't work either.

Creating the interface manually with `nmcli con add type vlan con-name bond0.1000 dev bond0 id 1000 ip4 10.68.97.3/31 gw4 10.68.97.2` works as expected and creates the following:
```
===============================================================================
                    Connection profile details (bond0.1000)
===============================================================================
connection.id:                          bond0.1000
connection.uuid:                        759a01be-e2d9-4e73-8e0c-b9bb9c6da100
connection.stable-id:                   --
connection.type:                        vlan
connection.interface-name:              --
connection.autoconnect:                 yes
connection.autoconnect-priority:        0
connection.autoconnect-retries:         -1 (default)
connection.multi-connect:               0 (default)
connection.auth-retries:                -1
connection.timestamp:                   1628007747
connection.read-only:                   no
connection.permissions:                 --
connection.zone:                        --
connection.master:                      --
connection.slave-type:                  --
connection.autoconnect-slaves:          -1 (default)
connection.secondaries:                 --
connection.gateway-ping-timeout:        0
connection.metered:                     unknown
connection.lldp:                        default
connection.mdns:                        -1 (default)
connection.llmnr:                       -1 (default)
connection.wait-device-timeout:         -1
-------------------------------------------------------------------------------
802-3-ethernet.port:                    --
802-3-ethernet.speed:                   0
802-3-ethernet.duplex:                  --
802-3-ethernet.auto-negotiate:          no
802-3-ethernet.mac-address:             --
802-3-ethernet.cloned-mac-address:      --
802-3-ethernet.generate-mac-address-mask:--
802-3-ethernet.mac-address-blacklist:   --
802-3-ethernet.mtu:                     auto
802-3-ethernet.s390-subchannels:        --
802-3-ethernet.s390-nettype:            --
802-3-ethernet.s390-options:            --
802-3-ethernet.wake-on-lan:             default
802-3-ethernet.wake-on-lan-password:    --
-------------------------------------------------------------------------------
ipv4.method:                            manual
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.addresses:                         10.68.97.3/31
ipv4.gateway:                           10.68.97.2
ipv4.routes:                            --
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.routing-rules:                     --
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-iaid:                         --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.dhcp-hostname-flags:               0x0 (none)
ipv4.never-default:                     no
ipv4.may-fail:                          yes
ipv4.dad-timeout:                       -1 (default)
ipv4.dhcp-vendor-class-identifier:      --
-------------------------------------------------------------------------------
ipv6.method:                            auto
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.addresses:                         --
ipv6.gateway:                           --
ipv6.routes:                            --
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.routing-rules:                     --
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.ra-timeout:                        0 (default)
ipv6.dhcp-duid:                         --
ipv6.dhcp-iaid:                         --
ipv6.dhcp-timeout:                      0 (default)
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.dhcp-hostname-flags:               0x0 (none)
ipv6.token:                             --
-------------------------------------------------------------------------------
vlan.parent:                            bond0
vlan.id:                                1000
vlan.flags:                             1 (REORDER_HEADERS)
vlan.ingress-priority-map:              --
vlan.egress-priority-map:               --
-------------------------------------------------------------------------------
proxy.method:                           none
proxy.browser-only:                     no
proxy.pac-url:                          --
proxy.pac-script:                       --
-------------------------------------------------------------------------------
```

The difference between the two is `ipv4.never-default` which is set to `yes` via the network role by default. I have tried using the `auto_gateway: yes` option but `ipv4.never-default` would still be `yes` and the `ipv4.gateway` null.

The OS is Centos 8.

**Comment by enricobachiorrini** [comment] 2021-08-04 10:45
The NetworkManager's log file shows the following warning whatever the value of `auto_gateway`:

`<warn>  [1628073515.8113] ifcfg-rh:     GATEWAY will be ignored when DEFROUTE is disabled`

**Comment by jaedolph** [comment] 2021-12-31 06:29
Hi @enricobachiorrini, I tested your config and couldn't seem to replicate the issue. Unsure what is causing the behavior you are seeing but it does seem related to the `ipv4.never-default` setting.

I used a Centos 8 Stream VM so may have been using a slightly different version of NetworkManager to what you had (my VM used version 1.32.0-0.4.el8). Which version of NetworkManager and the role were you using?

I did some testing and can confirm that if you use nmcli to turn on `ipv4.never-default` on a connection, NetworkManager seems to remove the gateway from the config. I also tested this with the underlying bond interface and the same behavior occurs.

> The difference between the two is ipv4.never-default which is set to yes via the network role by default. I have tried using the auto_gateway: yes option but ipv4.never-default would still be yes and the ipv4.gateway null.

The role should not modify the `ipv4.never-default` setting unless you specifically add it to the config like this using the `auto_gateway` parameter. The only thing I can think of is that this was an existing interface with `ipv4.never-default=yes` set and the role did not modify it. The role should override this value if you explicitly set `auto_gateway: yes` in your playbook though.

Did your config look something like this when you attempted to turn on the setting?
```
network_connections:
  - name: bond0
    state: up

  - name: bond0.1000
    state: up
    type: vlan
    parent: bond0
    vlan:
      id: 1000
    ip:
      auto_gateway: yes
      address:
        - 10.68.97.3/31
      gateway4: 10.68.97.2
```

## My attempt to replicate the issue

I manually created the bond0 interface using nmcli, then ran this playbook:
```
- name: replicate issue 413
  hosts: all
  vars:
    network_connections:
      - name: bond0
        state: up

      - name: bond0.1000
        state: up
        type: vlan
        parent: bond0
        vlan:
          id: 1000
        ip:
          address:
            - 10.68.97.3/31
          gateway4: 10.68.97.2
  roles:
    - linux-system-roles.network
```
This gave the following connection properties:
```
[root@localhost ~]# nmcli con show bond0.1000 | cat
connection.id:                          bond0.1000
connection.uuid:                        712d12ee-9eba-4058-b67e-0b30f47c7990
connection.stable-id:                   --
connection.type:                        vlan
connection.interface-name:              bond0.1000
connection.autoconnect:                 yes
connection.autoconnect-priority:        0
connection.autoconnect-retries:         -1 (default)
connection.multi-connect:               0 (default)
connection.auth-retries:                -1
connection.timestamp:                   1640929605
connection.read-only:                   no
connection.permissions:                 --
connection.zone:                        --
connection.master:                      --
connection.slave-type:                  --
connection.autoconnect-slaves:          -1 (default)
connection.secondaries:                 --
connection.gateway-ping-timeout:        0
connection.metered:                     unknown
connection.lldp:                        default
connection.mdns:                        -1 (default)
connection.llmnr:                       -1 (default)
connection.wait-device-timeout:         -1
802-3-ethernet.port:                    --
802-3-ethernet.speed:                   0
802-3-ethernet.duplex:                  --
802-3-ethernet.auto-negotiate:          no
802-3-ethernet.mac-address:             --
802-3-ethernet.cloned-mac-address:      --
802-3-ethernet.generate-mac-address-mask:--
802-3-ethernet.mac-address-blacklist:   --
802-3-ethernet.mtu:                     auto
802-3-ethernet.s390-subchannels:        --
802-3-ethernet.s390-nettype:            --
802-3-ethernet.s390-options:            --
802-3-ethernet.wake-on-lan:             default
802-3-ethernet.wake-on-lan-password:    --
802-3-ethernet.accept-all-mac-addresses:-1 (default)
ipv4.method:                            manual
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.addresses:                         10.68.97.3/31
ipv4.gateway:                           10.68.97.2
ipv4.routes:                            --
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.routing-rules:                     --
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-iaid:                         --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.dhcp-hostname-flags:               0x0 (none)
ipv4.never-default:                     no
ipv4.may-fail:                          yes
ipv4.dad-timeout:                       -1 (default)
ipv4.dhcp-vendor-class-identifier:      --
ipv4.dhcp-reject-servers:               --
ipv6.method:                            auto
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.addresses:                         --
ipv6.gateway:                           --
ipv6.routes:                            --
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.routing-rules:                     --
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.ra-timeout:                        0 (default)
ipv6.dhcp-duid:                         --
ipv6.dhcp-iaid:                         --
ipv6.dhcp-timeout:                      0 (default)
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.dhcp-hostname-flags:               0x0 (none)
ipv6.token:                             --
vlan.parent:                            7aaf20e2-28bd-4b66-bb7e-66d46173263a
vlan.id:                                1000
vlan.flags:                             1 (REORDER_HEADERS)
vlan.ingress-priority-map:              --
vlan.egress-priority-map:               --
proxy.method:                           none
proxy.browser-only:                     no
proxy.pac-url:                          --
proxy.pac-script:                       --
GENERAL.NAME:                           bond0.1000
GENERAL.UUID:                           712d12ee-9eba-4058-b67e-0b30f47c7990
GENERAL.DEVICES:                        bond0.1000
GENERAL.IP-IFACE:                       bond0.1000
GENERAL.STATE:                          activated
GENERAL.DEFAULT:                        no
GENERAL.DEFAULT6:                       no
GENERAL.SPEC-OBJECT:                    --
GENERAL.VPN:                            no
GENERAL.DBUS-PATH:                      /org/freedesktop/NetworkManager/ActiveConnection/14
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/Settings/9
GENERAL.ZONE:                           --
GENERAL.MASTER-PATH:                    --
IP4.ADDRESS[1]:                         10.68.97.3/31
IP4.GATEWAY:                            10.68.97.2
IP4.ROUTE[1]:                           dst = 10.68.97.2/31, nh = 0.0.0.0, mt = 400
IP4.ROUTE[2]:                           dst = 0.0.0.0/0, nh = 10.68.97.2, mt = 400
IP6.ADDRESS[1]:                         fe80::cbb:296b:9d5a:382e/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 400
IP6.ROUTE[2]:                           dst = ff00::/8, nh = ::, mt = 256, table=255
```
As you can see, the gateway is correctly set and ipv4.never-default is set to "no" which should be the default for the role.

**Comment by tyll** [comment] 2022-02-14 21:18
@enricobachiorrini thank you for your report. Since @jaedolph reported that the bug cannot be reproduced, I will close this report. Please file a new issue or reopen this one (not sure if this is possible) if necessary, if you have more information.

**Closed by tyll** 2022-02-14 21:18 UTC
