### ISSUE TITLE
Trying to change state to down says conn doesnt exists

### ISSUE THREAD

**Issue by xbnextel** [linux-system-roles/network#28] opened 2018-03-01 12:38 UTC
error:
TASK [rhel-system-roles.network : Configure networking connection profiles] *********
fatal: [satellite]: FAILED! => {"changed": false, "msg": "configuration error: connections[0].name: state \"down\" references non-existing connection \"ens192\""}

playbook:
---
- hosts: satellite
  vars:
    network_connections:
      - name: ens192
        state: down
  roles: 
    - role: rhel-system-roles.network

System:
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

# nmcli co show
NOMBRE  UUID                                  TIPO            DISPOSITIVO 
ens192  2ee0adce-59b5-49c3-93f9-7b1df88b2bae  802-3-ethernet  ens192      
ens224  e4014630-448b-5ad3-4992-f4678202147c  802-3-ethernet  ens224 

# nmcli co down ens192

La conexión 'ens192' fue desactivada correctamente (ruta activa D-Bus: /org/freedesktop/NetworkManager/ActiveConnection/21)
Error: no se encontraron todas las conexiones activas.

**Comment by pcahyna** [comment] 2019-03-12 15:21
Is it fixed by PR #52 ?

**Comment by tyll** [comment] 2020-04-20 18:12
> Is it fixed by PR #52 ?

Since we did not hear otherwise and we do not have any idea how to reproduce this (there are tests that check this AFAICS), I assume it is.

**Closed by tyll** 2020-04-20 18:12 UTC
